channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - notebook
  - matplotlib
  - xarray
  - numpy
  - scipy
  - cartopy
  - pandas
  - dask
  - netcdf4
  - seaborn
  - pip
  - bottleneck # required by xclim, but can't be installed with pip
  - pip:
     - metpy
     - xclim # version on conda-forge appears to not be compatible with cartopy
     - openpyxl
     - pymannkendall
